//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.ReportsTextClassifierAi
{
    using ICSSoft.STORMNET;


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ReportType.
    /// </summary>
    // *** Start programmer edit section *** (ReportType CustomAttributes)

    // *** End programmer edit section *** (ReportType CustomAttributes)
    [AutoAltered()]
    [Caption("Тип отчета")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ReportTypeE", new string[] {
            "Name",
            "TypeId"})]
    [View("ReportTypeL", new string[] {
            "Name",
            "TypeId"})]
    public class ReportType : ICSSoft.STORMNET.DataObject
    {

        private string fName;

        private string fTypeId;

        // *** Start programmer edit section *** (ReportType CustomMembers)

        // *** End programmer edit section *** (ReportType CustomMembers)


        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (ReportType.Name CustomAttributes)

        // *** End programmer edit section *** (ReportType.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (ReportType.Name Get start)

                // *** End programmer edit section *** (ReportType.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (ReportType.Name Get end)

                // *** End programmer edit section *** (ReportType.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ReportType.Name Set start)

                // *** End programmer edit section *** (ReportType.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (ReportType.Name Set end)

                // *** End programmer edit section *** (ReportType.Name Set end)
            }
        }

        /// <summary>
        /// TypeId.
        /// </summary>
        // *** Start programmer edit section *** (ReportType.TypeId CustomAttributes)

        // *** End programmer edit section *** (ReportType.TypeId CustomAttributes)
        [StrLen(255)]
        public virtual string TypeId
        {
            get
            {
                // *** Start programmer edit section *** (ReportType.TypeId Get start)

                // *** End programmer edit section *** (ReportType.TypeId Get start)
                string result = this.fTypeId;
                // *** Start programmer edit section *** (ReportType.TypeId Get end)

                // *** End programmer edit section *** (ReportType.TypeId Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ReportType.TypeId Set start)

                // *** End programmer edit section *** (ReportType.TypeId Set start)
                this.fTypeId = value;
                // *** Start programmer edit section *** (ReportType.TypeId Set end)

                // *** End programmer edit section *** (ReportType.TypeId Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// Тип отчета.
            /// </summary>
            public static ICSSoft.STORMNET.View ReportTypeE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ReportTypeE", typeof(IIS.ReportsTextClassifierAi.ReportType));
                }
            }

            /// <summary>
            /// Типы отчетов.
            /// </summary>
            public static ICSSoft.STORMNET.View ReportTypeL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ReportTypeL", typeof(IIS.ReportsTextClassifierAi.ReportType));
                }
            }
        }
    }
}

