FROM python:3.11

WORKDIR /fastapiproject

# Устанавливает зависимости.
COPY /src/ScikitLearnClassifier/requirements.txt /fastapiproject/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /fastapiproject/requirements.txt

# Копируем файлы приложения и запускаем.
COPY /src/ScikitLearnClassifier/app /fastapiproject/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
