FROM python:3.11

WORKDIR /fastapiproject

# Копирование модели обученного классификатора
COPY /src/ScikitLearnClassifier/classifier_model.pkl /fastapiproject/classifier_model.pkl

# Устанавливает зависимости.
COPY /src/ScikitLearnClassifier/requirements.txt /fastapiproject/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /fastapiproject/requirements.txt
RUN pip install python-multipart

# Копируем файлы приложения и запускаем.
COPY /src/ScikitLearnClassifier/app /fastapiproject/app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80"]
