name: SonarCloud
on:
  push:
    branches:
      - feature-234099-workflows
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  python-project-check:
    name: Python analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/ScikitLearnClassifier/requirements.txt
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
            projectBaseDir: ./src/ScikitLearnClassifier
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
